#ifndef __MHSCPU_SDK_H
#define __MHSCPU_SDK_H

#include "typedefine.h"
#include "..\sdk\Libraries\Device\MegaHunt\mhscpu\Include\mhscpu.h"
#include "..\sdk\Libraries\Device\MegaHunt\mhscpu\Include\system_mhscpu.h"
#include "..\sdk\Libraries\MHSCPU_Driver\inc\mhscpu_adc.h"
#include "..\sdk\Libraries\MHSCPU_Driver\inc\mhscpu_dac.h"
#include "..\sdk\Libraries\MHSCPU_Driver\inc\mhscpu_bpk.h"
#include "..\sdk\Libraries\MHSCPU_Driver\inc\mhscpu_crc.h"
//#include "..\sdk\Libraries\MHSCPU_Driver\inc\mhscpu_dcmi.h"
#include "..\sdk\Libraries\MHSCPU_Driver\inc\mhscpu_dma.h"
#include "..\sdk\Libraries\MHSCPU_Driver\inc\mhscpu_exti.h"
//#include "..\sdk\Libraries\MHSCPU_Driver\inc\mhscpu_flash.h"
#include "..\sdk\Libraries\MHSCPU_Driver\inc\mhscpu_qspi.h"
#include "..\sdk\Libraries\MHSCPU_Driver\inc\mhscpu_hspim.h"
#include "..\sdk\Libraries\MHSCPU_Driver\inc\mhscpu_gpio.h"
//#include "..\sdk\Libraries\MHSCPU_Driver\inc\mhscpu_img_cop.h"
#include "..\sdk\Libraries\MHSCPU_Driver\inc\mhscpu_it.h"
//#include "..\sdk\Libraries\MHSCPU_Driver\inc\mhscpu_lcdi.h"
#include "..\sdk\Libraries\MHSCPU_Driver\inc\mhscpu_msr.h"
//#include "..\sdk\Libraries\MHSCPU_Driver\inc\mhscpu_rec.h"
#include "..\sdk\Libraries\MHSCPU_Driver\inc\mhscpu_rtc.h"
#include "..\sdk\Libraries\MHSCPU_Driver\inc\mhscpu_sensor.h"
#include "..\sdk\Libraries\MHSCPU_Driver\inc\mhscpu_spi.h"
#include "..\sdk\Libraries\MHSCPU_Driver\inc\mhscpu_ssc.h"
#include "..\sdk\Libraries\MHSCPU_Driver\inc\mhscpu_sysctrl.h"
#include "..\sdk\Libraries\MHSCPU_Driver\inc\mhscpu_timer.h"
#include "..\sdk\Libraries\MHSCPU_Driver\inc\mhscpu_trng.h"
#include "..\sdk\Libraries\MHSCPU_Driver\inc\mhscpu_uart.h"
#include "..\sdk\Libraries\MHSCPU_Driver\inc\mhscpu_wdt.h"
#include "..\sdk\Libraries\MHSCPU_Driver\inc\misc.h"
#include "..\sdk\Libraries\MHSCPU_Driver\inc\mhscpu_cache.h"
#include "..\sdk\Libraries\MHSCPU_Driver\inc\emvlib\iso7816_3.h"
//#include "..\sdk\Libraries\MHSCPU_Driver\inc\securelib\mh_rsa.h"
//#include "..\sdk\Libraries\MHSCPU_Driver\inc\securelib\mh_rand.h"
#include "..\sdk\Libraries\MHSCPU_Driver\inc\mhscpu_dcmi.h"
#include "..\sdk\Libraries\MHSCPU_Driver\inc\mhscpu_i2c.h"
#include "..\sdk\Libraries\MHSCPU_Driver\inc\mhscpu_lcdi.h"
#include "..\sdk\Libraries\MHSCPU_Driver\inc\mhscpu_sci.h"
#include "..\sdk\Libraries\MHSCPU_Driver\inc\mhscpu_msr.h"


#endif

